import numpy as np
import pandas as pd
from typing import Dict, Any, Tuple, Optional, List

from src.config import (
    ANNUAL_NIM_RATE,
    VIP_OUTREACH_COST,
    VIP_SAVE_RATE,
    DIGITAL_INCENTIVE_COST,
    DIGITAL_SAVE_RATE,
    HIGH_BALANCE_THRESHOLD,
    DEFAULT_DECISION_THRESHOLD,
)


def calculate_nim_value(balance: float, nim_rate: float = ANNUAL_NIM_RATE) -> float:
    """Calculate annual Net Interest Margin generated by a deposit balance."""
    return float(balance * nim_rate)


def evaluate_retention_economics(
    balance: float,
    churn_proba: float,
    threshold: float = DEFAULT_DECISION_THRESHOLD,
    nim_rate: float = ANNUAL_NIM_RATE,
    high_balance_cutoff: float = HIGH_BALANCE_THRESHOLD,
    vip_cost: float = VIP_OUTREACH_COST,
    vip_save_rate: float = VIP_SAVE_RATE,
    digital_cost: float = DIGITAL_INCENTIVE_COST,
    digital_save_rate: float = DIGITAL_SAVE_RATE,
) -> Dict[str, Any]:
    """
    Compute customer-level financial metrics, intervention cost, and expected net savings.
    """
    annual_nim = calculate_nim_value(balance, nim_rate)
    is_targeted = bool(churn_proba >= threshold)
    is_vip = bool(balance >= high_balance_cutoff)

    if is_targeted:
        if is_vip:
            campaign_type = "VIP_RELATIONSHIP_MANAGER"
            cost = vip_cost
            save_rate = vip_save_rate
            recommended_action = "Assign Dedicated Relationship Manager for Wealth Retention & Fee Review"
            tier = "CRITICAL" if churn_proba >= 0.70 else "HIGH"
            quadrant = "Tier 1: High Value / High Risk (RM VIP Outreach)"
        else:
            campaign_type = "DIGITAL_INCENTIVE"
            cost = digital_cost
            save_rate = digital_save_rate
            recommended_action = "Trigger Automated Digital Fee-Waiver & Premium Card Upgrade"
            tier = "HIGH" if churn_proba >= 0.70 else "MEDIUM"
            quadrant = "Tier 2: Low Value / High Risk (Digital Offer)"

        # Expected Value = (Probability of Churn * Save Rate * Annual NIM) - Intervention Cost
        expected_savings = (churn_proba * save_rate * annual_nim) - cost
    else:
        campaign_type = "NO_INTERVENTION"
        cost = 0.0
        save_rate = 0.0
        expected_savings = 0.0
        tier = "LOW"
        if is_vip:
            quadrant = "Tier 3: High Value / Low Risk (Wealth Cross-Sell)"
            recommended_action = "Proactive Wealth Management Cross-Sell & Advisory Review"
        else:
            quadrant = "Tier 4: Low Value / Low Risk (Standard Service)"
            recommended_action = "Maintain Standard Digital Engagement & Loyalty Rewards"

    return {
        "annual_nim_at_risk": round(annual_nim, 2),
        "is_targeted": is_targeted,
        "is_vip": is_vip,
        "tier": tier,
        "quadrant": quadrant,
        "campaign_type": campaign_type,
        "intervention_cost": cost,
        "save_rate": save_rate,
        "expected_net_savings": round(expected_savings, 2),
        "recommended_action": recommended_action,
    }


def optimize_decision_threshold(
    y_true: np.ndarray,
    y_proba: np.ndarray,
    balances: np.ndarray,
    nim_rate: float = ANNUAL_NIM_RATE,
    high_balance_cutoff: float = HIGH_BALANCE_THRESHOLD,
    vip_cost: float = VIP_OUTREACH_COST,
    vip_save_rate: float = VIP_SAVE_RATE,
    digital_cost: float = DIGITAL_INCENTIVE_COST,
    digital_save_rate: float = DIGITAL_SAVE_RATE,
    threshold_range: Tuple[float, float, int] = (0.05, 0.95, 91),
) -> Dict[str, Any]:
    """
    Search over candidate probability thresholds to find the threshold p*
    that maximizes Total Portfolio Net Profit Saved (€/$).
    """
    thresholds = np.linspace(threshold_range[0], threshold_range[1], threshold_range[2])
    net_profits = []
    retention_costs = []
    gross_nim_saved = []

    y_true_bool = y_true.astype(bool)
    is_vip_arr = balances >= high_balance_cutoff
    nim_values = balances * nim_rate

    for th in thresholds:
        targeted = y_proba >= th

        # True Positives (actual churners targeted)
        tp_mask = targeted & y_true_bool
        # False Positives (non-churners targeted by mistake)
        fp_mask = targeted & (~y_true_bool)

        # VIP targets
        tp_vip = tp_mask & is_vip_arr
        fp_vip = fp_mask & is_vip_arr

        # Digital targets
        tp_dig = tp_mask & (~is_vip_arr)
        fp_dig = fp_mask & (~is_vip_arr)

        # Revenue saved
        nim_saved_vip = np.sum(nim_values[tp_vip]) * vip_save_rate
        nim_saved_dig = np.sum(nim_values[tp_dig]) * digital_save_rate
        total_gross_saved = float(nim_saved_vip + nim_saved_dig)

        # Costs incurred (for both TP and FP targeted customers)
        total_costs = float(
            (np.sum(tp_vip) + np.sum(fp_vip)) * vip_cost
            + (np.sum(tp_dig) + np.sum(fp_dig)) * digital_cost
        )

        net_profit = total_gross_saved - total_costs
        net_profits.append(net_profit)
        retention_costs.append(total_costs)
        gross_nim_saved.append(total_gross_saved)

    best_idx = int(np.argmax(net_profits))
    optimal_threshold = float(thresholds[best_idx])
    max_profit = float(net_profits[best_idx])

    # Compare with naive threshold (0.50)
    idx_50 = int(np.argmin(np.abs(thresholds - 0.50)))
    profit_at_50 = float(net_profits[idx_50])
    profit_lift_vs_50 = max_profit - profit_at_50

    return {
        "optimal_threshold": round(optimal_threshold, 3),
        "max_net_profit_saved": round(max_profit, 2),
        "profit_at_default_50": round(profit_at_50, 2),
        "profit_lift_over_default": round(profit_lift_vs_50, 2),
        "threshold_curve": {
            "thresholds": thresholds.tolist(),
            "net_profits": net_profits,
            "retention_costs": retention_costs,
            "gross_nim_saved": gross_nim_saved,
        },
    }


def segment_portfolio_customers(
    df: pd.DataFrame,
    churn_probabilities: np.ndarray,
    threshold: float = DEFAULT_DECISION_THRESHOLD,
    high_balance_cutoff: float = HIGH_BALANCE_THRESHOLD,
) -> pd.DataFrame:
    """
    Assign every customer in the portfolio to the 4-Tier Strategic Retention Matrix.
    """
    df_out = df.copy()
    df_out["ChurnProbability"] = churn_probabilities
    df_out["IsTargeted"] = df_out["ChurnProbability"] >= threshold
    df_out["IsVIP"] = df_out["Balance"] >= high_balance_cutoff

    conditions = [
        (df_out["IsVIP"] & df_out["IsTargeted"]),
        ((~df_out["IsVIP"]) & df_out["IsTargeted"]),
        (df_out["IsVIP"] & (~df_out["IsTargeted"])),
        ((~df_out["IsVIP"]) & (~df_out["IsTargeted"])),
    ]

    tier_labels = [
        "Tier 1: High Value / High Risk (RM VIP Outreach)",
        "Tier 2: Low Value / High Risk (Digital Offer)",
        "Tier 3: High Value / Low Risk (Wealth Cross-Sell)",
        "Tier 4: Low Value / Low Risk (Standard Service)",
    ]

    action_labels = [
        "Assign Dedicated Relationship Manager for Fee/Rate Review",
        "Trigger Automated Digital Retention Incentive & Points Boost",
        "Proactive Wealth Management Advisory & Portfolio Cross-Sell",
        "Maintain Standard Service & Routine Engagement",
    ]

    df_out["RetentionTier"] = np.select(conditions, tier_labels, default="Tier 4: Low Value / Low Risk (Standard Service)")
    df_out["RecommendedAction"] = np.select(conditions, action_labels, default="Maintain Standard Service")

    return df_out


def compute_portfolio_deposit_risk(
    df: pd.DataFrame,
    churn_probabilities: np.ndarray,
    threshold: float = DEFAULT_DECISION_THRESHOLD,
    nim_rate: float = ANNUAL_NIM_RATE,
    high_balance_cutoff: float = HIGH_BALANCE_THRESHOLD,
    vip_cost: float = VIP_OUTREACH_COST,
    vip_save_rate: float = VIP_SAVE_RATE,
    digital_cost: float = DIGITAL_INCENTIVE_COST,
    digital_save_rate: float = DIGITAL_SAVE_RATE,
) -> Dict[str, Any]:
    """
    Compute aggregate portfolio-level financial exposure and campaign ROI.
    """
    segmented_df = segment_portfolio_customers(df, churn_probabilities, threshold, high_balance_cutoff)
    total_deposits = float(segmented_df["Balance"].sum())
    
    # Deposits at risk (predicted churners)
    targeted_mask = segmented_df["IsTargeted"]
    deposits_at_risk = float(segmented_df.loc[targeted_mask, "Balance"].sum())
    annual_nim_at_risk = deposits_at_risk * nim_rate

    # Campaign metrics
    tier1_count = int((segmented_df["RetentionTier"].str.startswith("Tier 1")).sum())
    tier2_count = int((segmented_df["RetentionTier"].str.startswith("Tier 2")).sum())
    tier3_count = int((segmented_df["RetentionTier"].str.startswith("Tier 3")).sum())
    tier4_count = int((segmented_df["RetentionTier"].str.startswith("Tier 4")).sum())

    total_campaign_cost = (tier1_count * vip_cost) + (tier2_count * digital_cost)

    # Expected gross NIM saved
    t1_mask = segmented_df["RetentionTier"].str.startswith("Tier 1")
    t2_mask = segmented_df["RetentionTier"].str.startswith("Tier 2")
    gross_nim_saved = (
        float((segmented_df.loc[t1_mask, "Balance"] * segmented_df.loc[t1_mask, "ChurnProbability"]).sum() * nim_rate * vip_save_rate)
        + float((segmented_df.loc[t2_mask, "Balance"] * segmented_df.loc[t2_mask, "ChurnProbability"]).sum() * nim_rate * digital_save_rate)
    )
    net_savings = gross_nim_saved - total_campaign_cost
    roi_pct = (net_savings / total_campaign_cost * 100.0) if total_campaign_cost > 0 else 0.0

    return {
        "total_portfolio_customers": len(segmented_df),
        "total_portfolio_deposits": round(total_deposits, 2),
        "deposits_at_risk": round(deposits_at_risk, 2),
        "annual_nim_at_risk": round(annual_nim_at_risk, 2),
        "total_targeted_customers": int(targeted_mask.sum()),
        "total_campaign_cost": round(total_campaign_cost, 2),
        "expected_gross_nim_saved": round(gross_nim_saved, 2),
        "expected_net_nim_saved": round(net_savings, 2),
        "campaign_roi_pct": round(roi_pct, 2),
        "tier_breakdown": {
            "tier_1_rm_vip": tier1_count,
            "tier_2_digital_incentive": tier2_count,
            "tier_3_wealth_cross_sell": tier3_count,
            "tier_4_standard_service": tier4_count,
        },
    }

